### PR TITLE
Etapa1

### PR DESCRIPTION
**Pull request by elsebita10**
se unió el back en java con un front en react (configuracion). La funcionalidad es mostrar listado de usuarios de la base

### CODE REVIEW

**Comment by elsebita10** [comment]
Lo ideal seria
[numeroDeStory]/[descripcionEn3o4palabrasDeLoQueConsisteLaHistoria]

**Comment by juliaesc** [comment]
¿Puede ser así?

1/consultaInfoCtaCta

😙


<http://www.buildingways.com.ar>  [image:
https://juliaescobio.wordpress.com/]
<https://juliaescobio.wordpress.com/>  [image:
https://www.facebook.com/Building-Ways-556441037895043/]
<https://www.facebook.com/buildingways.com.ar/>  [image:
https://twitter.com/buildingways] <https://twitter.com/buildingways>  [image:
https://www.linkedin.com/in/juliaescobio/]
<https://www.linkedin.com/in/juliaescobio/>  [image:
https://plus.google.com/u/0/+JuliaEscobio]
<https://plus.google.com/u/0/+JuliaEscobio>

2018-05-07 9:27 GMT-03:00 Sebastian Antonelli <notifications@github.com>:

**Comment by elsebita10** [comment]
jajaja que seria CtaCta?

ponelo completo, consultarInfoCuentaCorriente


2018-05-07 9:35 GMT-03:00 Julia Escobio <notifications@github.com>:

**Comment by juliaesc** [comment]
Ya le puse obtenerCuentaCorriente como me dijiste, y ya borré etapa1.
😙


<http://www.buildingways.com.ar>  [image:
https://juliaescobio.wordpress.com/]
<https://juliaescobio.wordpress.com/>  [image:
https://www.facebook.com/Building-Ways-556441037895043/]
<https://www.facebook.com/buildingways.com.ar/>  [image:
https://twitter.com/buildingways] <https://twitter.com/buildingways>  [image:
https://www.linkedin.com/in/juliaescobio/]
<https://www.linkedin.com/in/juliaescobio/>  [image:
https://plus.google.com/u/0/+JuliaEscobio]
<https://plus.google.com/u/0/+JuliaEscobio>

2018-05-07 11:47 GMT-03:00 Sebastian Antonelli <notifications@github.com>:

**Pull request merged**
